version: '2'

services:
  mongo:
    image: docker.io/library/mongo:4.4.29
    container_name: microcks-db
    volumes:
      # Podman does not create missing folders, so we need to use an existing one
      # Add the ":z" flag to get SELinux configured automatically
      - "./microcks-data:/data/db"
    #user: "501:1000"

  postman:
    image: quay.io/microcks/microcks-postman-runtime:0.6.0
    container_name: microcks-postman-runtime

  app:
    depends_on:
      - mongo
      - postman
    image: quay.io/microcks/microcks:1.11.0
    container_name: microcks
    volumes:
      - "./config:/deployments/config"
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_URI=mongodb://microcks-db:27017
      - SPRING_DATA_MONGODB_DATABASE=microcks
      - POSTMAN_RUNNER_URL=http://postman:3000
      - TEST_CALLBACK_URL=http://microcks:8080
      - SERVICES_UPDATE_INTERVAL=0 0 0/2 * * *
      - KEYCLOAK_ENABLED=false
      #- MAX_UPLOAD_FILE_SIZE=3MB
