services:
  mongo:
    image: docker.io/library/mongo:4.4.29
    container_name: microcks-db
    volumes:
      # Podman does not create missing folders, so we need to use an existing one
      # Add the ":z" flag to get SELinux configured automatically
      - "./microcks-data:/data/db"
    #user: "501:1000"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 1s
      retries: 3

  postman:
    image: quay.io/microcks/microcks-postman-runtime:0.7.1
    container_name: microcks-postman-runtime
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      start_period: 5s
      interval: 20s
      timeout: 3s
      retries: 3

  app:
    depends_on:
      - mongo
      - postman
    image: quay.io/microcks/microcks:1.13.2
    container_name: microcks
    volumes:
      - "./config:/deployments/config"
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_URI=mongodb://microcks-db:27017
      - SPRING_DATA_MONGODB_DATABASE=microcks
      - POSTMAN_RUNNER_URL=http://postman:3000
      - TEST_CALLBACK_URL=http://microcks:8080
      - SERVICES_UPDATE_INTERVAL=0 0 0/2 * * *
      - KEYCLOAK_ENABLED=false
      #- LOGGING_LEVEL_IO_GITHUB_MICROCKS=DEBUG
      #- MAX_UPLOAD_FILE_SIZE=3MB
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      start_period: 35s
      interval: 10s
      timeout: 3s
      retries: 3
