services:
  nats:
    image: nats:2.9.8-alpine3.16
    container_name: microcks-nats
    ports:
      - 4222:4222
      - 8222:8222
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "4222"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
