{
 "title": "microcks-overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job Name",
    "query": {
     "query": "label_values(process_uptime_seconds,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "RED Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Performance metrics overview per service during selected time range",
   "type": "table",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(service,version)(rate(http_server_requests_seconds_count{job=\"$job\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (service,version) (increase(http_server_requests_seconds_sum{job=\"$job\"}[$__range])) / sum by (service,version) (increase(http_server_requests_seconds_count{job=\"$job\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(.95,sum(rate(http_server_requests_seconds_bucket{job=\"$job\"}[$__range])) by(service,version,le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(.99,sum(rate(http_server_requests_seconds_bucket{job=\"$job\"}[$__range])) by(service,version,le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(service,version)(increase(http_server_requests_seconds_count{job=\"$job\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(service,version) (http_server_requests_seconds_count{job=\"$job\", status=~\"2.*\",}) / sum by(service,version) (http_server_requests_seconds_count{job=\"$job\"})*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time distribution in seconds over selected time range",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (increase(http_server_requests_seconds_bucket{job=\"$job\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPS per service & version over last minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(service,version)(rate(http_server_requests_seconds_count{job=\"$job\"}[1m]))",
     "legendFormat": "{{service}} | {{version}}"
    }
   ]
  },
  {
   "title": "P99 per service & version over last 5 min",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate(http_server_requests_seconds_bucket{job=\"$job\"}[5m])) by(service,version, le))",
     "legendFormat": "{{service}} | {{version}}"
    }
   ]
  },
  {
   "title": "P95 per service & version over last 5 min",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.95,sum(rate(http_server_requests_seconds_bucket{job=\"$job\"}[5m])) by(service,version, le))",
     "legendFormat": "{{service}} | {{version}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Log of All Spring Boot Apps",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{job=\"$job\"} | json | line_format `\u001b[1m{{if .level }}{{alignRight 5 .level}}{{else if .severity}}{{alignRight 5 .severity}}{{end}}\u001b[0m \u001b[90m[{{alignRight 10 .resources_service_instance_id}}{{if .attributes_thread_name}}/{{alignRight 20 .attributes_thread_name}}{{else if eq \"java\" .resources_telemetry_sdk_language }}                    {{end}}]\u001b[0m \u001b[36m{{if .instrumentation_scope_name }}{{alignRight 40 .instrumentation_scope_name}}{{end}}\u001b[0m {{.body}} {{if .traceid}} \u001b[37m\u001b[3m[traceid={{.traceid}}]{{end}}`",
     "maxLines": 80
    }
   ]
  }
 ]
}