name: Microcks Health Check

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install docker-compose
        run: |
          apt-get update && apt-get install -y docker-compose

      - name: Set up Docker Compose
        run: docker-compose version

      - name: Start Microcks services
        run: |
          docker-compose -f ./install/docker-compose/docker-compose.yml up -d

      - name: Wait for containers to be healthy
        run: ./scripts/container-health-check.sh

      - name: Tear down Microcks services
        if: always()
        run: docker-compose -f ./install/docker-compose/docker-compose.yml down
